### ISSUE TITLE
No obj file is created after running convert.py

### ISSUE THREAD

**Issue by SouravKB** [Vorono4ka/scw2obj#1]
I tried to covert warriorprincess scw file to obj file. I tried it multiple times, but the expected obj file is never created.

When I run the convert.py  in python shell, it said the conversion was successful, but obj folder was empty.

I am using windows 10 OS-64bit, 8GB RAM, with python 3.8 installed.

**Comment by danila-schelkov** [comment]
Hello, can you give me a screenshots?
